language: ruby
notifications:
  irc: "irc.freenode.org#cells"
rvm:
  - 1.9.3
  - 1.8.7
gemfile:
  - Gemfile
  - gemfiles/Gemfile.mongoid-2.4
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.mongoid-2.4
  allow_failures:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.mongoid-2.4
